### ISSUE TITLE
Can't access to eu server

### ISSUE THREAD

**Issue by ghost** [seevik2580/tor-ip-changer#100]
Hi, I'm andrea and I'm from Italy. I'm trying to use your program, but when I try to start the service speicificating a European country, the system crashes and won't connect. From what I noticed the ip change works only if entered on “random”, although I would like the ip to change every x minutes via only Italian ip, thank you very much!
I attach a picture as an example:
<img width="957" alt="Untitled" src="https://github.com/user-attachments/assets/de39f2b2-cb83-4757-b837-6289759fb4b7" />

**Comment by seevik2580** [comment]
hi.
this software is just some sort of "GUI" for tor service. i am no developer of tor service so I have no influence on whether a country works or not
