### ISSUE TITLE
Download issue

### ISSUE THREAD

**Issue by chrisovato** [seevik2580/tor-ip-changer#13]
Why IPchanger need 3.4.x version? I have only installed the newest 3.7.x? Could you update it?

**Comment by seevik2580** [comment]
you can run ipchanger with python 3.7.x without no problem.. you just need to install requirements with `pip` 
`pip install pycurl pysocks urllib3`
with python 3.4.4 pip wont install pycurl so thats why i provide an exe file installation for pycurl module. up from python 3.5.0 you can use `pip install pycurl`
also if you want to build ipchanger exe file, there is a problem with py2exe. official mainained py2exe version does not support python up from version 3.5.0, you have to use modified one. from [HERE](https://github.com/albertosottile/py2exe/releases)
download wheel file for python version you are using and then install it with `pip install file.whl`
then everything will work fine

![image](https://user-images.githubusercontent.com/22060747/87153934-9226aa80-c2b8-11ea-855b-4325d6950d98.png)

**Comment by chrisovato** [comment]
I need to build IPchanger from start.pyw to exe file with my custom settings, made in start.pyw file. How can I do this?

**Comment by seevik2580** [comment]
> also if you want to build ipchanger exe file, there is a problem with py2exe. official mainained py2exe version does not support python up from version 3.5.0, you have to use modified one. from HERE

so, again....
**you need to download **py2exe** which supports python 3.7, download it from here** [HERE](https://github.com/albertosottile/py2exe/releases)
download **WHEEL**(py2exe-0.9.3.2-cp37-none-win_amd64.whl) and install it with pip `pip install py2exe-0.9.3.2-cp37-none-win_amd64.whl`

**after that you can use build.bat**

you can also provide me some log files or terminal output so i can see by myself what you did wrong

**Comment by chrisovato** [comment]
I get an error ```Could not locate script resource```
I have installed py2exe-0.9.3.2-cp37-none-win_amd64.whl
Idk where I can find logs

**Comment by seevik2580** [comment]
well thats not enough info for me, just copy paste whole terminal output after start build.bat
like this

you can also try to compile without build.bat, try `python setup-ipchanger.py`
```
(ipchanger)> **python setup-ipchanger.py**
running py2exe

  9 missing Modules
  ------------------
? Queue                               imported from urllib3.util.queue
? backports                           imported from urllib3.packages.ssl_match_hostname
? brotli                              imported from urllib3.response, urllib3.util.request
? collections.Callable                imported from socks
? collections.Mapping                 imported from urllib3._collections
? collections.MutableMapping          imported from urllib3._collections
? idna                                imported from urllib3.util.url
? readline                            imported from cmd, code, pdb
? win_inet_pton                       imported from socks
Building 'dist\ipchanger.exe'.
Building shared code archive 'dist\Lib\library.zip'.
Copy c:\users\seva\.conda\envs\ipchanger\python37.dll to dist
Copy C:\Users\Seva\.conda\envs\ipchanger\DLLs\select.pyd to dist\Lib\select.pyd
Copy C:\Users\Seva\.conda\envs\ipchanger\DLLs\pyexpat.pyd to dist\Lib\pyexpat.pyd
Copy C:\Users\Seva\.conda\envs\ipchanger\DLLs\unicodedata.pyd to dist\Lib\unicodedata.pyd
Copy C:\Users\Seva\.conda\envs\ipchanger\DLLs\_socket.pyd to dist\Lib\_socket.pyd
Copy C:\Users\Seva\.conda\envs\ipchanger\DLLs\_bz2.pyd to dist\Lib\_bz2.pyd
Copy C:\Users\Seva\.conda\envs\ipchanger\DLLs\_lzma.pyd to dist\Lib\_lzma.pyd
Copy C:\Users\Seva\.conda\envs\ipchanger\DLLs\_hashlib.pyd to dist\Lib\_hashlib.pyd
Copy C:\Users\Seva\.conda\envs\ipchanger\DLLs\_ssl.pyd to dist\Lib\_ssl.pyd
Copy C:\Users\Seva\.conda\envs\ipchanger\DLLs\_ctypes.pyd to dist\Lib\_ctypes.pyd
Copy C:\Users\Seva\.conda\envs\ipchanger\DLLs\_tkinter.pyd to dist\Lib\_tkinter.pyd
Copy C:\Users\Seva\.conda\envs\ipchanger\DLLs\_multiprocessing.pyd to dist\Lib\_multiprocessing.pyd
Copy C:\Users\Seva\.conda\envs\ipchanger\DLLs\_decimal.pyd to dist\Lib\_decimal.pyd
Copy C:\Users\Seva\.conda\envs\ipchanger\DLLs\_queue.pyd to dist\Lib\_queue.pyd
Copy C:\Users\Seva\.conda\envs\ipchanger\lib\site-packages\pycurl.cp37-win_amd64.pyd to dist\Lib\pycurl.pyd
Copy DLL C:\Users\Seva\.conda\envs\ipchanger\Library\bin\libssl-1_1-x64.dll to dist\Lib
Copy DLL C:\Users\Seva\.conda\envs\ipchanger\DLLs\tcl86t.dll to dist\Lib
Copy DLL C:\Users\Seva\.conda\envs\ipchanger\api-ms-win-crt-time-l1-1-0.dll to dist\Lib
Copy DLL C:\Users\Seva\.conda\envs\ipchanger\api-ms-win-crt-process-l1-1-0.dll to dist\Lib
Copy DLL C:\Users\Seva\.conda\envs\ipchanger\api-ms-win-crt-string-l1-1-0.dll to dist\Lib
Copy DLL C:\Users\Seva\.conda\envs\ipchanger\api-ms-win-crt-heap-l1-1-0.dll to dist\Lib
Copy DLL C:\Users\Seva\.conda\envs\ipchanger\api-ms-win-crt-locale-l1-1-0.dll to dist\Lib
Copy DLL C:\Users\Seva\.conda\envs\ipchanger\VCRUNTIME140.dll to dist\Lib
Copy DLL C:\Users\Seva\.conda\envs\ipchanger\api-ms-win-crt-math-l1-1-0.dll to dist\Lib
Copy DLL C:\Users\Seva\.conda\envs\ipchanger\api-ms-win-crt-convert-l1-1-0.dll to dist\Lib
Copy DLL C:\Users\Seva\.conda\envs\ipchanger\api-ms-win-crt-conio-l1-1-0.dll to dist\Lib
Copy DLL C:\Users\Seva\.conda\envs\ipchanger\api-ms-win-crt-utility-l1-1-0.dll to dist\Lib
Copy DLL C:\Users\Seva\.conda\envs\ipchanger\api-ms-win-crt-environment-l1-1-0.dll to dist\Lib
Copy DLL C:\Users\Seva\.conda\envs\ipchanger\DLLs\tk86t.dll to dist\Lib
Copy DLL C:\Users\Seva\.conda\envs\ipchanger\api-ms-win-crt-stdio-l1-1-0.dll to dist\Lib
Copy DLL C:\Users\Seva\.conda\envs\ipchanger\api-ms-win-crt-filesystem-l1-1-0.dll to dist\Lib
Copy DLL C:\Users\Seva\.conda\envs\ipchanger\Library\bin\libcrypto-1_1-x64.dll to dist\Lib
Copy DLL C:\Users\Seva\.conda\envs\ipchanger\api-ms-win-crt-runtime-l1-1-0.dll to dist\Lib
```

**Comment by chrisovato** [comment]
```
11 missing Modules
  ------------------
? Queue                               imported from urllib3.util.queue
? backports                           imported from urllib3.packages.ssl_match_hostname
? brotli                              imported from urllib3.response, urllib3.util.request
? collections.Callable                imported from socks
? collections.Mapping                 imported from urllib3._collections
? collections.MutableMapping          imported from urllib3._collections
? idna                                imported from urllib3.util.url
? pycurl                              imported from start
? readline                            imported from cmd, code, pdb
? test                                imported from multiprocessing.util
? win_inet_pton                       imported from socks
Building 'dist\ipchanger.exe'.
error: [WinError 87] Parametr jest niepoprawny.
```

**Comment by seevik2580** [comment]
ok, remove **dist** folder also **pychache** folder and try again, also try it with **administrator privileges** maybe your python cannot write to that folder. also which exactly version of python u run ? 3.7.4 ? 3.7.5 ? 3.7.6 ? 3.7.7 ? i tried version 3.7.7 and it worked fine. i cant reproduce this error :(

**Comment by seevik2580** [comment]
also it could be a bug mentioned here [https://github.com/pytest-dev/pytest/issues/5724](https://github.com/pytest-dev/pytest/issues/5724)

**Comment by chrisovato** [comment]
I do not have **pychache** folder and I have removed the dist folder.
```error: [WinError 87] The parameter is not valid. ```
The same error.

**Comment by seevik2580** [comment]
ok ill try with clean python 3.7.8. a moment please :)

**Comment by seevik2580** [comment]
oh, there was an error in start.pyw i forgot to import string module at the top of script
fixed in commit [b87203309eab5dd31ecaf800541cc68d0abb3100](https://github.com/seevik2580/tor-ip-changer/commit/b87203309eab5dd31ecaf800541cc68d0abb3100)

try now

**Comment by chrisovato** [comment]
I get the same error

**Comment by seevik2580** [comment]
well thats weird because it worked for me with python 3.7.8, 3.7.7, 3.7.6, 3.7.x. so it must be something wrong with py2exe
did you made any changes inside setup-ipchanger.py ?

**Comment by chrisovato** [comment]
Not yet.

**Comment by seevik2580** [comment]
try to use miniconda and install python 3.7 with virtualenv but its weird.. i had clean installation of python 3.7.8 with no modules installed ... i install just `pip install pycurl pysocks urllib3 py2exe-0.9.3.2-cp37-none-win_amd64.whl`
`python ipchanger.py` works ok
`python setup-ipchanger.py` works ok
`build.bat` also works ok

if you run just `python ipchanger.py` will it start without any errors ?

**Comment by chrisovato** [comment]
If I run ```pyhon ipchanger.py``` I get this:
``` 
import tkinter.ttk, random, _thread, time, tkinter.scrolledtext, socket, re, logging, os,sys, multiprocessing, subprocess, pycurl, io, webbrowser,argparse, urllib3, string
ModuleNotFoundError: No module named 'pycurl'```

**Comment by chrisovato** [comment]
If I type ``` python ipchanger.py ``` It starts with no errors

**Comment by seevik2580** [comment]
then it must be something wrong with py2exe
there is an alternative method how to build exe file
`pip install pyinstaller`
`pyinstaller -F -w ipchanger.py`
it will create single exe file inside folder Dist..
try and let me know

**Comment by seevik2580** [comment]
according to some research, i found that [WinError 87] could occur if your path to folder where ipchanger.py file is is too long.. long folder names etc...
`For older versions of Windows that don't support long directory and file names, an exception with a more informative error message than "[WinError 87]" should be thrown.` 
how long is your path to ipchanger.py ? which version of windows 10 do you use ? start cmd and type  `winver`,. 
i have Windows 10 version 2004 build 19041.329

**Comment by chrisovato** [comment]
Same version of windows 10. 
Path to ipchanger: C:\Users\Chrisovato\Desktop\ipchanger\source-code-win\1.2.4
Pyinstaller also does not work :(

**Comment by seevik2580** [comment]
well, then its beyond my capabilities :( its not an error with ipchanger itself if you can run `python ipchanger.exe` with no errors.
you can try install some virtual machine with clean windows 10 installation, and then try it here

**Comment by chrisovato** [comment]
Ok I will try, thanks for the help anyway 👍

**Comment by seevik2580** [comment]
or if you want .. you can publish start.pyw file and i can try to build exe file for you ?

**Comment by chrisovato** [comment]
Thanks, I will use .py file 👍

**Comment by seevik2580** [comment]
alright 👍
