### ISSUE TITLE
Problem in ipchanger !

### ISSUE THREAD

**Issue by odaiasd** [seevik2580/tor-ip-changer#25]
@seevik2580  when i choose palestine (ps) country its stuck on (45% : Asking for relay descriptors )
can you help me to fix it ?
Thank you

**Comment by seevik2580** [comment]
hello, this is not an error with ipchanger itself. if you get stucked at Asking for relay descriptors, it offten means that there are no relays in that specific country.. you can check that for youself..
for example Palestine [with this link](https://metrics.torproject.org/rs.html#search/country:ps)
another for USA its [this link](https://metrics.torproject.org/rs.html#search/country:us)
and another for GB its [this link](https://metrics.torproject.org/rs.html#search/country:gb)
so if there are no relays in Palestine, you cant simply connect to tor network. you have to select different country

**Comment by odaiasd** [comment]
Thank you

**Comment by seevik2580** [comment]
if you get stucked at this with every country you select or even without country selection maybe your ISP has blocked tor traffic. there are some ISPs which does not allow tor traffic inside their network, so you can try to use **Bridge** method to try to connect to tor network. its in settings, select **Use Bridges YES**. then try to start tor server again. hope it helps
