### ISSUE TITLE
VERY IMPORTANT QUESTION !

### ISSUE THREAD

**Issue by odaiasd** [seevik2580/tor-ip-changer#26]
Is there a way to change the IP every second in the Google Chrome ( NOT FIREFOX )?
Please help me, because I want this so much.
Thank you , 
sincerely,
odaiasd.

**Comment by seevik2580** [comment]
yes you can, google chrome just use system proxy settings unlike firefox which does have his own proxy settings build-in.
go to **Windows Start**, search for **Internet Options**, select tab **Connections**, then click **LAN Settings**.. then select **Use a proxy server for your LAN**, if some IP occured in field Address and also port number in field Port then just remove it and then click **advanced**, then type proxy IP (127.0.0.1) and port (9050) in **socks** field, hit ok three times and done.

![image](https://user-images.githubusercontent.com/22060747/88862396-874c9f00-d200-11ea-8926-9c40c5cbd583.png)
![image](https://user-images.githubusercontent.com/22060747/88862416-90d60700-d200-11ea-8500-9ef2b18812d6.png)

or if this is too complicated for you, you can use a google chrome extensions like "SOCKS Proxy" [Link here](https://chrome.google.com/webstore/detail/socks-proxy/odiakldnmmpjabkemfboijigageaelcn)

hope it helps :)

**Comment by odaiasd** [comment]
Thank you so much 
you are the best in the world
