### ISSUE TITLE
Do you have a way to hack Facebook?

### ISSUE THREAD

**Issue by odaiasd** [seevik2580/tor-ip-changer#27]
Hi ,
I know I asked a lot, but your programs designs are very beautiful and interesting
So do you have a way to hack Facebook from computer or anyway else ? 
Thank you !♥
sincerely,
odaiasd.

**Comment by seevik2580** [comment]
there is always a way to hack something because it was created by man.
unfortunately i won't share any method here

**Comment by odaiasd** [comment]
OK
Can I contact you elsewhere?
Because I really want to learn it, please

**Comment by seevik2580** [comment]
sorry but no. i won't teach you or anyone else how to hack.
it is better if you try to search some forums or websites about this.

eg:
https://www.blackhatworld.com/
https://hackforums.net/
http://www.phrack.org/
https://0day.today/

i'll be happy to help with any problem in ipchanger but that's all.

**Comment by odaiasd** [comment]
okay then
In your description you say you are cracker.
can you crack this program for me ? 
https://gohacking.net to the platinum version .
if the answer is yes ( reply )
if the answer is no ( close the issue )

**Comment by seevik2580** [comment]
there is nothing to crack, this program is fake. its written in C# without any obfuscation or compression, so its easy to use dotPeek to decompile it and search inside whats it doing.

a couple of things ... 

1) there is no activation method this program
2) program doesnt hack anything, it just says shits about trial version...
3) according to virustotal, hybrid-analysis and other sites there is 
 malware joined with exe file
4) i will close every other issues which are not for ipchanger.. 

please read github terms about issues.

have a great day 

![image](https://user-images.githubusercontent.com/22060747/90024726-7cd8dd80-dcb5-11ea-9b02-378c6d31c095.png)
![image](https://user-images.githubusercontent.com/22060747/90024759-882c0900-dcb5-11ea-9d7f-de46d2e05cbb.png)

**Comment by odaiasd** [comment]
Thank you

Sorry if I was annoying you.

في الأربعاء، ١٢ آب، ٢٠٢٠ ٥:٠٥ م Šéva <notifications@github.com> كتب:

**Comment by seevik2580** [comment]
no problem. i answered nicely. it's just because created issues has to be for project not for third party stuff.
