### ISSUE TITLE
Do you have an ipchanger for the phone?

### ISSUE THREAD

**Issue by odaiasd** [seevik2580/tor-ip-changer#28]
hello,
Do you have an ipchanger for the phone?

**Comment by seevik2580** [comment]
hello, unfortunately not

**Comment by lilcsz** [comment]
Did you tried to run on termux?

**Comment by seevik2580** [comment]
sadly i don't have android phone, but theoreticaly if you can manage dependencies for linux environment [(LINK HERE)](https://github.com/seevik2580/tor-ip-changer/tree/master/source-code-linux) then yes, you can try to use termux
