### ISSUE TITLE
Change ip by telnet 

### ISSUE THREAD

**Issue by chrisovato** [seevik2580/tor-ip-changer#30]
Hi, 
I am running 5 different IP's(5 proxies: ```9050, 9051, 9052, 9053, 9054```). 
How to change IP only in first(```9050```) and second(```9051```) proxy by telnet in python?

**Comment by seevik2580** [comment]
for windows it will be available in version 1.2.6. 
for now its only available in linux version by telnet command `changeip onceport 9050`
for windows it will be the same way. 
1.2.6 planned to be released soon... this week i hope.

**Comment by chrisovato** [comment]
How to install ipchanger on linux(ubuntu 20.0)?

**Comment by seevik2580** [comment]
https://github.com/seevik2580/tor-ip-changer/tree/master/source-code-linux
