### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by chrisovato** [seevik2580/tor-ip-changer#34]
Hi, 
it would be awesome if we can run and use tor-ip-changer with one command `docker-compose up -d` on linux.

**Comment by seevik2580** [comment]
hello,
its a great idea, you can try it with [docker-compose.yml](https://raw.githubusercontent.com/seevik2580/tor-ip-changer/master/docker-compose.yml)
its not perfect, but it works. by time i will update linux version of ipchanger to have all features that windows version has

**Comment by seevik2580** [comment]
#37
