### ISSUE TITLE
I NEED HELP !

### ISSUE THREAD

**Issue by odaiasd** [seevik2580/tor-ip-changer#43]
Hello, first of all , I want to thnk for all what you do ♥
second, there is a problem when i start tor ip changer it comes like that ..

![image](https://user-images.githubusercontent.com/68323558/109256217-3cc6eb80-77fe-11eb-9d52-1ee84c16777a.png)
how can we solve it ?

**Comment by odaiasd** [comment]
Hello ?

**Comment by seevik2580** [comment]
Hello, my time was consumed by my job... in nutshell: 0xc000007b is not ipchanger error.. its Windows error 
which version of OS you are using ? if windows 7 then try to upgrade to service pack 2, try to install Microsoft Visual C++ 2010 x64 Redistributable, also net frameworks 3.5 + 4+
also try these steps: https://forums.tomshardware.com/threads/windows-7-64-bit-error-0xc000007b.1669967/

so there is something wrong with your windows OS ... i tried to reproduce this with several fresh installed windows PC with windows 7/8/8.1/10 and everything worked fine. fix or reinstall your pc. i cannot help with this.

**Comment by odaiasd** [comment]
THANKS
