### ISSUE TITLE
Want to crack proggram 

### ISSUE THREAD

**Issue by jasenbaswods** [seevik2580/tor-ip-changer#44]
Hi .
Can you help me please ?
I have a program that i can't open it without a serial number ...i googled about serian number in the internet, but i didn't find anything useful 
Can you help me please ? 

The program i want to crack  on this link : https://www.mediafire.com/file/6qmjq63u5k6i85j/New_folder.rar

**Comment by seevik2580** [comment]
not ipchanger issue....
