### ISSUE TITLE
ipchanger problem

### ISSUE THREAD

**Issue by sipeneco** [seevik2580/tor-ip-changer#46]
![erro](https://user-images.githubusercontent.com/80340718/117854980-eeb07880-b281-11eb-8bb2-a9ee8f185f25.png)
 Hi,

So I downloaded the folder when I double clicke ipchanger.exe, this error in the image appears.

How can I solve it?

Cheers

**Comment by seevik2580** [comment]
hello, thank you for your report. 
do u use last version of ipchanger (1.2.7) ? can you attach that logfile to this issue?

**Comment by sipeneco** [comment]
thanks for the quick reponse
I have the last version (1.2.7)
about logfile, I alreday search it, in all over the folder and I didn't  find it
