### ISSUE TITLE
question

### ISSUE THREAD

**Issue by ribhupanwar** [seevik2580/tor-ip-changer#48]
is there any way to run my own proxy list thorough tor ip changer

**Comment by seevik2580** [comment]
sadly no, it would be nice to have this feature, but it fetch ips only from tor network

**Comment by ribhupanwar** [comment]
sir can we change proxy source like other proxy site to fetch proxy if yes then where should i change.

**Comment by seevik2580** [comment]
no, it works only with tor network, that's why it's called "Tor Ip Changer"
