### ISSUE TITLE
OSX support

### ISSUE THREAD

**Issue by renekroka** [seevik2580/tor-ip-changer#49]
Hello,
First of all thanks for releasing this great tool, tested on Windows 10 and works how its supposed to.

I have tried running IPchanger on OSX (big sur) however app is throwing errors(I kinda expected that as its in experimental build),
when can we expect IPChanger to be fully working on OSX? or atleast how to set it up so its working.

Thank you!

**Comment by seevik2580** [comment]
Hello, sadly i dont have macOS so i cant continue to maintain OSX version... maybe in future... 
meanwhile u can try to use docker version which should work .. install some X11 server like Quartz.. then use command `xhost +`  and then start container with `docker run -p 14999:14999 -p 9050:9050 -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix seevik2580/tor-ip-changer` or use docker-compose

**Comment by renekroka** [comment]
Thank you, I will try that solution! :)
