### ISSUE TITLE
Windows defender says it includes a trojan

### ISSUE THREAD

**Issue by KentelDevelopment** [seevik2580/tor-ip-changer#50]
Hello, I'm using this for my bot projects(changing IP) and windows defender deletes the file when I open the script. Can you help me?

**Comment by seevik2580** [comment]
make exception for folder where you have ipchanger. there is no trojan in my script, but defender and other antiviruses does not like my download function when it download tor.exe file from my github repository.

**Comment by KentelDevelopment** [comment]
I understand, I liked your software thank you for developing this
