### ISSUE TITLE
Never same IP again - feature request

### ISSUE THREAD

**Issue by renekroka** [seevik2580/tor-ip-changer#52]
Hello,
As title says, I would appericate feature where you can choose that you won"t ever get assigned same IP as before when using the switch ip feature. I would love to see this feature implemented and you might recieve nice btc tip for it :)

**Comment by seevik2580** [comment]
i tried some tests and its not much difficult and it works like i said :D when i deplete all addresses then tor start to gave me errors.
![image](https://user-images.githubusercontent.com/22060747/131236230-b1075313-42b5-4f52-969b-5e1b142f4cd7.png)

example: 
blacklisted: 120 seconds
change interval: 10 seconds
country: czech republic
number of exitNodes: 5

![image](https://user-images.githubusercontent.com/22060747/131236219-3af090d5-c64f-4e8f-a085-1a87aef70a97.png)
![image](https://user-images.githubusercontent.com/22060747/131236595-9edb3fe5-939f-4fa7-a17a-3663fe68a573.png)

in nutshell: ipchanger checks this every changing interval if an ip and time now minus their timestamps are lower than unique time in settings. if no then ip is whitelisted again, if yes, it keeps blacklisted.

i managed this even for multiproxy feature where every single proxy has its own blacklist
![image](https://user-images.githubusercontent.com/22060747/131236679-9cf63a96-6f6b-48f6-acad-3e4230e1a2fc.png)

the difficult part is to what to do if everything is depleted :D

my ideas: 
1) i make button to flush all blacklisted ips
2) automatically whitelist first blacklisted ip in list
3) i make window to select which ip can be whitelisted permanently

do you have any ideas ? 😄

**Comment by renekroka** [comment]
Thanks for working on this, what about once all IPs are used / blacklisted we wait until new set of unused ips are ready and assign them, once those newly assigned ips are used / blacklisted, we repeat the cycle of waiting for unused ones.

ipchanger will create a list of used ips to make sure they will never be assigned again, the user can choose if only for current ipchanger session, or for all sessions ever.

**Comment by seevik2580** [comment]
well that sounds great, i think i can make it :)

**Comment by seevik2580** [comment]
its done, well amost.. i have to finish some little things
- exe for windows
- new changelog
- refactoring git repository because i unified script for linux and windows together
- new Dockerfile

i will try to publish till end of weekend

![image](https://user-images.githubusercontent.com/22060747/132049652-964ff2a5-379d-4b61-9283-a7c87d05706d.png)

**Comment by seevik2580** [comment]
published https://github.com/seevik2580/tor-ip-changer/commit/62ac7f72be45a3e31d746ad204b71d172148ce30

**Comment by renekroka** [comment]
Hi thanks for publishing it so quickly, i dont have much time rn to test it out, but i will soon hopefully and also send u Bitcoin tip, thanks a lot :)

**Comment by seevik2580** [comment]
thanks, i appreciate it. if you find any bugs, feel free to report it. and also if you have any other good feature requests :)
