### ISSUE TITLE
Can you spot the issue?

### ISSUE THREAD

**Issue by PauloChoupinaIPB** [seevik2580/tor-ip-changer#55]
Hi, I have been using successfully the tor-ip-changer for quiet some time now, but with this last update something went wrong, at least for me.

I keep getting:
|127.0.0.1:9050 |random   Changing OK but unable to connect|

In the logs I get: 
Sep 28 08:58:01.000 [warn] You specified a public address '0.0.0.0:9050' for SocksPort. Other people on the Internet might find your computer and use it as an open proxy. Please don't allow this unless you have a good reason.

but on the main window i have:
************************************************************
Autostart OFF. 
API server binded to 127.0.0.1:14999 (local) OK.
------------------------------------------------------------Checking files. 
No missing files
------------------------------------------------------------TOR server starting using direct connection. 
Always obtain unique IP OFF
Please wait ... 
0% - Starting 
5% - Connecting to a relay 
10% - Connected to a relay 
14% - Handshaking with a relay 
25% - Asking for networkstatus consensus 
30% - Loading networkstatus consensus 
45% - Asking for relay descriptors 
50% - Loading relay descriptors 
51% - Loading relay descriptors 
63% - Loading relay descriptors 
68% - Loading relay descriptors 
80% - Connecting to a relay to build circuits 
89% - Finishing handshake with a relay to build circuits 
95% - Establishing a Tor circuit 
100% - Done 
TOR server started 
DNS server started 
------------------------------------------------------------Proxy list:
127.0.0.1:9050

**Comment by seevik2580** [comment]
Hello,
`Changing OK but unable to connect` in this version is the same as `Changing OK - Resolving timeout` in version 1.2.7.
it only indicates that ipchanger is unable to resolve ip address that you obtained. i only change phrase. if you get this message are you able to resolve ip manualy when you go showip.net or anywhere else where you can find your ip ?
