### ISSUE TITLE
Smartproxy

### ISSUE THREAD

**Issue by chrisooo3** [seevik2580/tor-ip-changer#61]
Hi,
has anyone know how is possible that services like `https://smartproxy.com/` have over 40M available ip addresses? 

Do they have over 40M routers each with public ip address?

**Comment by seevik2580** [comment]
they can use kubernetes and microservices where you have thousands or millions of small containers and every container have its own ip address..

**Comment by chrisooo3** [comment]
Hi, 

what do you mean by microservices?

do you know some hosting service like aws that will allow to start over 40M pods/containers each with different ip?
