### ISSUE TITLE
i get this error

### ISSUE THREAD

**Issue by HazeOtto** [seevik2580/tor-ip-changer#62]
|127.0.0.1:9050 |random   Changing OK but unable to connect|

**Comment by seevik2580** [comment]
Hello,
`Changing OK but unable to connect` in this version is the same as `Changing OK - Resolving timeout` in version 1.2.7.
it only indicates that ipchanger is unable to resolve ip address that you obtained. its not error, its a feature. i only change phrase. if you get this message are you able to resolve ip manualy when you go showip.net or anywhere else where you can find your ip ?

**Comment by seevik2580** [comment]
if you are still unable to resolve IP with ip changer, can you attach logs here ?
