### ISSUE TITLE
Changing IP

### ISSUE THREAD

**Issue by Samar0946** [seevik2580/tor-ip-changer#63]
Hi, 
Thant always happened, I tried to add address and port manually, but still can't connect!!
any help?
![Screenshot 2021-12-22 043941](https://user-images.githubusercontent.com/84864247/147026101-a4cd306e-271d-4d8c-adb7-4781814fde6b.png)
![Screenshot 2021-12-21 150937](https://user-images.githubusercontent.com/84864247/147026105-6105ab96-2bd6-4d30-aa2d-bdf7339ff904.png)

**Comment by seevik2580** [comment]
Hello,
ipchanger is not build to co-work with tor browser. Tor browser uses its own tor client, and also ipchanger uses its own tor client
if you wish to use ipchanger, use it with regular browser (chrome, firefox, etc). also remove punctuation mark ":" from address line

**Comment by Samar0946** [comment]
how can I solve the "Changing OK but unable to connect " err?

**Comment by seevik2580** [comment]
can you attach logs here ?

**Comment by Samar0946** [comment]
Changelog: v1.3.0-8
************************************************************
Changed:
    - ssl validation to avoid ssl errors
************************************************************
Changelog: v1.3.0-7
************************************************************
Added:
    + option to always obtain unique ip for single proxy
            Options > Settings
    + option to always obtain unique ip for multi proxy
            Options > Settings  (with ipchanger -m)
    + API uniqueip port N (N=port number)
      set On/Off to obtain unique ip for proxy
    + API blacklist N (N=seconds)
      set blacklist ip for N seconds
    + blacklist.db inside Data/tordata/
    + Options > Settings > Blacklist GUI for specific proxy
    + torrc inside Data/tordata/
    + blacklist time inside settings.ini
    + option to set blacklist only for session
    + number of all exitNodes in status bar
    + number of exitNodes for specific country in console
    + duplicated message check and postpone to prevent spam
      to console
    + if single proxy deplete all ips it will postpone next
      change until new set of ips are available
    + if multi proxy deplete all ip it will postpone next
      change until new set of ips are available

Changed:
    + resolving ip with retry attempts if failed
    + Options > Settings GUI
    + Help > About GUI
    + settings.ini
    + python script multiplatform (windows and linux)
    + error reporting in console and logfiles

**Comment by seevik2580** [comment]
can you try to enable bridge connection in Options > Settings ? looks like connection to checkip.amazonaws.com timeouted every time

**Comment by Samar0946** [comment]
I did enabled it and restart it, my IP didn't change.

**Comment by seevik2580** [comment]
this indicates that the tor traffic is blocked. do you use any firewall ? windows firewall, 3rd party firewall ? antivirus etc ? if so then make permission for process tor.exe inside folder Tor and all his used ports.. if you use router firewall then i suggest to check if you doesnt block self-generated ssl certificate traffic which tor uses

**Comment by Samar0946** [comment]
I am sorry but it gives me the same error.
I stopped windows firewall and antivirus but it didn't work

**Comment by 1Megazone** [comment]
Dear Sir,
I wanna to know how to make the following option/setting :

'-m n' start multiple proxy n instances
example: ipchanger.exe -m 5
start proxy 5 times
with different ports
and generate list

I looking for you help and advice
thanks in advance

**Comment by seevik2580** [comment]
> Dear Sir, I wanna to know how to make the following option/setting :
> 
> '-m n' start multiple proxy n instances example: ipchanger.exe -m 5 start proxy 5 times with different ports and generate list
> 
> I looking for you help and advice thanks in advance

Hello, 
create shortcut from your ipchanger.exe and change your Target: like in picture below
![image](https://user-images.githubusercontent.com/22060747/185491517-105b5737-729c-440b-9c41-7f851ea60090.png)

**Comment by dkforce-dot** [comment]
please help fix my problem

the problem is that it keeps being stuck at 50%
and when i try to check & Repair it just says Failed...repeating 

anyone know why?
