### ISSUE TITLE
Internet connection cut off

### ISSUE THREAD

**Issue by alialhadad123** [seevik2580/tor-ip-changer#65]
hi
I'm working on Windows 10, I'm having a problem, the internet connection is cut off, when I use the private proxy address 127.0.0.1:9050, I'm using Chrome browser, I don't know why I'm facing this problem, when I restart everything as it was the connection comes back fine, also I turned off the firewall and antivirus but this did not work and the problem was not resolved, I will attach some pictures of the problem.
Thank you for your effort.
![خصائص الإنترنت 09_01_2022 11_53_26 ص](https://user-images.githubusercontent.com/97384695/148677875-546524d8-ae28-4878-9c41-ebb5ea2c31f2.png)
![TOR IP Changer _ Created by Seva _ v1 3 0-8 09_01_2022 11_52_07 ص](https://user-images.githubusercontent.com/97384695/148677884-8f0f9df1-100e-456d-9669-c89a2b91715e.png)
![‪www google com - Google Chrome‬ 09_01_2022 12_13_40 م](https://user-images.githubusercontent.com/97384695/148678054-f6bf3fc2-2b50-455e-b86f-9e2df49aeefc.png)

**Comment by seevik2580** [comment]
Hello,
remove ip and port from field, and click advanced, and write 127.0.0.1 into socks field and 9050 into port field in 4th row

![image](https://user-images.githubusercontent.com/22060747/148871587-fc4c7c74-30a9-487e-a076-345b5a34306f.png)

**Comment by alialhadad123** [comment]
It worked, thank you for your effort
