### ISSUE TITLE
Change proxy 

### ISSUE THREAD

**Issue by 9k12s** [seevik2580/tor-ip-changer#66]
Hello i love the program , only issue is connection is very poor, is there any way to get a faster connection? can i buy a new proxy and add it? thank you

**Comment by seevik2580** [comment]
Hi, unfortunately i can't do that.. if the speed is good or poor quality depends on the Tor developers and how good the connection nodes and exit nodes will be. i can't add any 3rd party proxies inside tor ip changer or tor network
