### ISSUE TITLE
ModuleNotFoundError: No module named 'tkinter'

### ISSUE THREAD

**Issue by ArshamCoder** [seevik2580/tor-ip-changer#67]
Hi 
when i run this command 'python setup-ipchanger-windows.py' it will make ipchanger.exe in dist folder.
When I want to run ipchanger.exe, it shows me this error :

`
Traceback (most recent call last):
  File "ipchanger.py", line 4, in <module>
ModuleNotFoundError: No module named 'tkinter'
`

my OS is Windows 10.

**Comment by seevik2580** [comment]
Hello,
do you install python with tkinter feature? 
![image](https://user-images.githubusercontent.com/22060747/148872084-dd971647-214a-4610-beb3-718c3ce05a1b.png)
