### ISSUE TITLE
Change IP through an external app

### ISSUE THREAD

**Issue by sulz47** [seevik2580/tor-ip-changer#7]
Hello I am trying to build an app which sends http requests to a website.
But i need proxies who change after every HTTP request
so while searching on google i found tor ip changer in which we can change ip after several X seconds and i read in an issue that it can now be changed on demand

so what i was thinking a way to change IP on demand via an external app through api

kindly let me know if this is possible as i want my app to send http requests via tor ips and it changes ip either after 30 http requests or after every http request but it needs to do this faster as my program is multithreaded and it cannot wait for like minutes untill a new ip shows up...

i want fluditity in this if this is possible...

**Comment by seevik2580** [comment]
Hello and sorry for late answer. i was consumed by my job :(
yes you can change ip with external app. in latest version 1.2.2 i make API commands through telnet
so you just need to telnet to localhost and port 14999 which is for communication with API.
it will support every programming lang where telnet library is supported.
for example:
php:
`$host = "localhost";`
`$port = "14999";`
`$timeout = "5";`
`$f=fsockopen($host,$port,$timeout);`
`if (!$f) {`
`        echo "not connected";`
`} else {`
`        echo "connected";`
`        echo fgets($f, 1024);`
`        fwrite($f,"changeip once\r\n");`
`        sleep(1);`
`        fwrite($f,"exit\r\n");`
`        echo fgets($f, 1024);`
`       fclose($f);`
`}`

python:
`import telnetlib`
`tn = telnetlib.Telnet('127.0.0.1', '14999', 5)`
`tn.write(b"changeip once\r\n")`
`tn.close`

**Comment by deshudiosh** [comment]
this is just perfect
