### ISSUE TITLE
Hey I love LOVE your project. There is nothing like it, but is there any way to change the proxy faster than 10 secs? For eg, even if I type in 1 sec or anything less than 10, the proxy still changes with a gap of about 10 seconds only. Please help, and thank you seevik!

### ISSUE THREAD

**Issue by harryspeaks** [seevik2580/tor-ip-changer#70]

**Comment by seevik2580** [comment]
Hi, thank you, i appreciate it. 
you can try to run with argument `-a 1` eg:   `ipchanger.exe -a 1` or `ipchanger.exe -a 3` `ipchanger.exe -a 5` .....
i have limitation in gui to change everything less than 10 seconds back to 10 seconds, its recommended not to change ip offten less than 10 seconds.. tor client can crash or stop work and you have to restart app.

**Comment by harryspeaks** [comment]
Thanks for the replying, seevik! I just tried what you said. But it is repeatedly showing "Changing OK but unable to connect" but I don't seem to have that issue with 10 secs gap. Is that what you meant by the tor client crash? Can it be remedied?

**Comment by seevik2580** [comment]
no, "Changing OK but unable to connect" means that your ip changed but you are unable to resolve what that ip address is in time gap. it cannot be fixed, its feature, not bug.

**Comment by harryspeaks** [comment]
Thank you!

**Comment by harryspeaks** [comment]
4 seconds work :)
