### ISSUE TITLE
Orange IPs(the ones I guess which are without speedstamps/timestamps) not working

### ISSUE THREAD

**Issue by harryspeaks** [seevik2580/tor-ip-changer#71]
Hi love your project! So innovative. If you don't mind, please answer this. I have kept my setting to "random" and during the 10s where orange ip is loaded, the webpage doesn't work. Whereas it works perfectly when the ip addresses are in white(I guess the one with speedstamps). Is there any way to rotate only ips which are white and avoid orange ones fully? Or is there any other solution to this?
![Uploading 20220323_231411.jpg…]()

**Comment by harryspeaks** [comment]
![Uploading 20220323_231411.jpg…]()

**Comment by seevik2580** [comment]
hello, unfortunately that's not possible right now. but i can make it happen in future update. thanks for idea

**Comment by harryspeaks** [comment]
> 

COOL! Waiting for the update. Thank you, seevik!

**Comment by mafiotul0** [comment]
hi how i cann make to add more shortcuts. if i click Tor Ip Changer / Setings show onyl 1 127.0.0.1:9050 ramdom..... 
i have see in your description cann add more rulls! how ?

sorry 4 bad english

**Comment by seevik2580** [comment]
> > 
> 
> COOL! Waiting for the update. Thank you, seevik! Any idea when it will be?

sorry no ETA yet, i am consumed by my job
