### ISSUE TITLE
Settings 

### ISSUE THREAD

**Issue by mafiotul0** [seevik2580/tor-ip-changer#72]
hi how i can make to add more shortcuts. if i click Tor Ip Changer / Settings show only 1 127.0.0.1:9050 Ramdom.....
i have see in your description can add more rulls! how ?
like this 
https://user-images.githubusercontent.com/22060747/131236679-9cf63a96-6f6b-48f6-acad-3e4230e1a2fc.png

sorry 4 bad english

**Comment by seevik2580** [comment]
hi, for example run `ipchanger.exe -m 10`

**Comment by mustafucxk** [comment]
Hi bro, ur app is legendary. Can you describe how to run the code you describe? thanks. `ipchanger.exe -m 10`
