### ISSUE TITLE
port duplication

### ISSUE THREAD

**Issue by alienfucxk** [seevik2580/tor-ip-changer#73]
can you please tell me how to run the `ipchanger.exe -m 10` port duplication code?

**Comment by seevik2580** [comment]
hi, you can't start 10 instances of tor with same port.
if you use -m 10 , first instance will have port 9050 and last instance will have port 9059

**Comment by mustafucxk** [comment]
I understand. Exactly what I want to ask is I don't know where to write this code? Can you tell? I couldn't find where to apply the shortcut codes.

**Comment by mustafucxk** [comment]
I want to increase the connection points like in this image. (https://github.com/seevik2580/tor-ip-changer/blob/master/screenshots/1.3.0-4.png). Where do I write your code?

**Comment by mustafucxk** [comment]
Where do I write the (exe shortcuts) codes in help.txt

**Comment by seevik2580** [comment]
![image](https://user-images.githubusercontent.com/22060747/166086210-ec427091-0014-46df-b543-5cf869cc3c5b.png)

**Comment by alienfucxk** [comment]
really thank you very much, good work
