### ISSUE TITLE
Is IP changer safe ? 

### ISSUE THREAD

**Issue by odiaoskdo** [seevik2580/tor-ip-changer#75]
Hello 
First of all, I would like to thank you for this wonderful program, but I have some questions that you can answer. The program is coming for me:
1- Does this program allow you to browse the Internet completely from a different IP or, for example, does Google discover this?
2- How many IPs does the State of Israel have?
3- Is there a program that gives me an unlimited number of IPs for the State of Israel?

Thank u So Much 
My greetings

**Comment by seevik2580** [comment]
Hello, thanks for that i really appreciate it.
IP changer is completely safe, in nutshell it is only GUI for TOR client which everyone can use with no limits (depends on your ISP/country regulations)
1. yes you can browse the Internet completely from a different IP with my ipchanger. But all TOR exit nodes are publicly available so there is always possibility for tracking mechanism. 
2. right now = Relays in IL: 13, ExitNodes in IL: 1, that means there is only 1 IP available to use.
3. no idea, im sorry

Hope it helps to answer your questions.
Cheers :)

**Comment by odiaoskdo** [comment]
Best one EVER !♥
