### ISSUE TITLE
No process found

### ISSUE THREAD

**Issue by masonsam** [seevik2580/tor-ip-changer#79]
when i run:
docker run -p 14999:14999 -p 9050:9050 -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix seevik2580/tor-ip-changer

Responds with:
tor: no process found
tail: no process found
where could be the problem?

Thank you, GJ

**Comment by seevik2580** [comment]
run `xhost +` before starting container
