### ISSUE TITLE
winerror 10054

### ISSUE THREAD

**Issue by robinranjanlive** [seevik2580/tor-ip-changer#82]
![image](https://user-images.githubusercontent.com/127621342/224503644-ed3c81b4-283f-40be-b3bb-1cded592c438.png)

**Comment by seevik2580** [comment]
looks like updater has problem to download files, it could be firewall issues, or isp issues, or ssl issues from your pc.. 
i suggest you to download it manualy from 
- https://raw.githubusercontent.com/seevik2580/tor-ip-changer/master/tor/UnRAR.exe 
- https://raw.githubusercontent.com/seevik2580/tor-ip-changer/master/dist/1.3.0/ipchanger.rar
and move both files where you have updater.exe, then updater will skip download process and extract it
