### ISSUE TITLE
tor-ip-changer not start

### ISSUE THREAD

**Issue by Madkhix** [seevik2580/tor-ip-changer#83]
When I changed it my port internet stopped working. I tried other ports but still not working and when i tried start the app its like:
![image](https://user-images.githubusercontent.com/62099980/226567777-55bbef6d-5e83-4dd0-8441-d205263fc93c.png)
Can you help me please?
Edited: If you need here is my log

Mar 21 11:49:50.902 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020133B0C548>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /summary

Mar 21 11:56:36.383 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection is forcibly closed by a remote host', None, 10054, None))': /summary?search=country:tr

and extra information i just can open app from updater when i clicked the ip-changer or tor nothing haappening.

Edited 2: When i try with tr its not working but with random choose its working perfect but i need ip change for tr. If you know the issue please let me know. Have a good day.

**Comment by seevik2580** [comment]
hello, can you try to open 
https://onionoo.torproject.org/summary?search=country:tr 
https://onionoo.torproject.org/summary?search=country:tr%20flag:exit
in your browser without app?
there is possibility that your ISP tried to block tor network

**Comment by Madkhix** [comment]
Hello again and thanks for your response.I can't connect both links in my browser without app. Is there anything I can do for this?   @seevik2580

**Comment by Madkhix** [comment]
Thank you for your help and quick response. I am trying to scrape data from a web site. I will try the method you said but I will probably have to solve my problem in another way because i need more ip address. Thank you very much again. Have a good day:)
