### ISSUE TITLE
Stops at: 45%

### ISSUE THREAD

**Issue by ItzDod0o** [seevik2580/tor-ip-changer#93]
The code stops at 10%. My ISP does block TOR servers, I tried using bridge and it stopped at 45% **(Asking for relay descriptors )**, I tried changing TOR bridges using https://bridges.torproject.org/bridges/?transport=obfs4 but still same problem

**Comment by TitoJhay** [comment]
is owner are didn't commented yet?

**Comment by TitoJhay** [comment]
![image_2024-06-10_001642459](https://github.com/seevik2580/tor-ip-changer/assets/109896739/f19020a1-a992-4a7f-9a7f-d09b7ee05464)
i solved this, you just setting off all of firewall, and add tor.exe, obfs4proxy.exe in allowed apps. and restart the app

**Comment by seevik2580** [comment]
please keep post issues only relevant to app itself, not to the tor service and ISPs
