### ISSUE TITLE
when location set to 'random' it ran perfectly, but when i change to other like e.g 'id' location it stop at 14% only

### ISSUE THREAD

**Issue by TitoJhay** [seevik2580/tor-ip-changer#94]
location set to 'RANDOM':
![image_2024-06-10_010633917](https://github.com/seevik2580/tor-ip-changer/assets/109896739/9deb7178-7802-498b-b5fb-0c03c18a2e95)

location set to 'ID':
![Uploading image_2024-06-10_010826534.png…]()

**Comment by seevik2580** [comment]
cannot reproduce your issue. first you need to be sure its not your network or ISP problem. feel free to post both log files from Logs folder.
- tor_YYYY_mm_dd_h_m_s.txt
- ipchanger_YYYY_mm_dd_h_m_s.txt

be sure to send logs after you close app so its generated properly.
![image](https://github.com/seevik2580/tor-ip-changer/assets/22060747/a8e9c647-10a8-4f46-a0a3-ea5ba29f2ce5)
