### ISSUE TITLE
ip changing not working on windows

### ISSUE THREAD

**Issue by mominurr** [seevik2580/tor-ip-changer#98]
I have tried a few times but it was not working. I tried on my laptop windows os and my PC but not working. When I was running ipchanger.exe it ran perfectly but when I looked at the browser(chrome) it did not change my PC IP. I am providing log files below that you can understand.  "127.0.0.1:9050" this proxy IP I added on "internet option".

[ipchanger_2024_10_12_23_35_45.log](https://github.com/user-attachments/files/17351023/ipchanger_2024_10_12_23_35_45.log)
[ipchanger_2024_10_13_00_04_07.log](https://github.com/user-attachments/files/17351024/ipchanger_2024_10_13_00_04_07.log)
[tor_2024_10_12_23_35_45.txt](https://github.com/user-attachments/files/17351025/tor_2024_10_12_23_35_45.txt)
[tor_2024_10_13_00_04_07.txt](https://github.com/user-attachments/files/17351026/tor_2024_10_13_00_04_07.txt)
![Screenshot 2024-10-13 000735](https://github.com/user-attachments/assets/db2ff1ec-aee4-4f5a-b41b-de5448c43e1d)

**Comment by Swagnik02** [comment]
Well i had this doubt from the begining, the tutorial shows the configuration for the 'Internet options' https://www.youtube.com/watch?v=htVw75kZYes

then i tried with edge it is working there but not in chrome !!

for reference 
![image](https://github.com/user-attachments/assets/1ae5906b-2523-468d-9019-ca04f52a49d5)
![image](https://github.com/user-attachments/assets/68a5fff3-790c-436e-9b02-701c37b509e8)

But i still expected this py app to work system-wide !

**Comment by mominurr** [comment]
I configured this problem and I solved it. The problem I faced in Chrome was installing a VPN extension in Chrome. That is why the tor IP changer did not work in Chrome. when I removed the extension from my Chrome then it worked in Chrome.

Thank you for your response.
