### ISSUE TITLE
file issue

### ISSUE THREAD

**Issue by Charan200316** [seevik2580/tor-ip-changer#99]
hi admin i had an issue regarding a file geoip and geoip6 when i gave check and repair while trying to download geoip file it shows failed repeating and when i check log there was this url
 https://raw.githubusercontent.com/torproject/tor/master/src/config/geoip 

 https://raw.githubusercontent.com/torproject/tor/master/src/config/geoip6 HTTP Error 404: Not Found

both these links hve 404 not found so please fix it and update sir my kind request

**Comment by seevik2580** [comment]
hi.
those files are not mandatory to work this software. if you still prefer to have them, you can download them manualy here:
https://gitlab.torproject.org/tpo/core/tor/-/raw/main/src/config/geoip
https://gitlab.torproject.org/tpo/core/tor/-/raw/main/src/config/geoip6
and copy them in folder ipchanger\Tor
